version: '3.1'

services:
  git-server:
    container_name: git-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    environment:
      - GIT_USERNAME=local
      - GIT_PASSWORD=local
      - RSYNC_EXCLUDE=excluded_file.txt
      - RSYNC_PROTECT=flux-sync
    volumes:
      - ./test/sample:/repos/mount/sample
