version: '3.1'

services:
  git-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    environment:
      - GIT_USERNAME=local
      - GIT_PASSWORD=local
      - RSYNC_EXCLUDE=dontsync
    volumes:
      - ./test/sample:/repos/mount/sample
